import os
import json
import shutil
from main import run_analysis, INPUT_DIR, OUTPUT_DIR

def setup_test_data():
    if not os.path.exists(INPUT_DIR): os.makedirs(INPUT_DIR)

    test_chat = """[10/10/2023, 10:00:00] User A: Olá, tudo bem?
[10/10/2023, 10:01:00] User B: Tudo ótimo! Você viu o documento anexado?
[10/10/2023, 10:02:00] User A: <anexado: documento_teste.pdf>
[10/10/2023, 10:03:00] User B: Vou verificar.
"""
    with open(os.path.join(INPUT_DIR, "test_chat.txt"), "w", encoding="utf-8") as f:
        f.write(test_chat)

def teardown_test_data():
    # Remove test files but keep the directories
    test_files = [
        os.path.join(INPUT_DIR, "test_chat.txt"),
    ]
    for f in test_files:
        if os.path.exists(f): os.remove(f)

    # Optionally clean output files generated by the test
    # (Matches chat_*.json, chat_*.txt, chat_*.md)
    for f in os.listdir(OUTPUT_DIR):
        if "test_chat" in f or "chat_" in f:
            # Be careful not to delete real user data if this runs in production
            # But for a clean test environment it's fine
            pass

def test_pipeline():
    print("🚀 Iniciando teste de integração...")
    setup_test_data()

    try:
        success = run_analysis()
        if not success:
            print("❌ Falha ao rodar a análise.")
            return

        # Verifica se os arquivos de saída foram gerados
        # O prefixo pode variar se o get_chat_metadata funcionar
        found_structured = False
        for f in os.listdir(OUTPUT_DIR):
            if f.endswith("_structured.json"):
                with open(os.path.join(OUTPUT_DIR, f), "r", encoding="utf-8") as jf:
                    data = json.load(jf)
                    if len(data) >= 3:
                        found_structured = True
                        print(f"✅ JSON estruturado gerado com {len(data)} mensagens.")

        if not found_structured:
            print("❌ Arquivo structured.json não encontrado ou vazio.")

    finally:
        # teardown_test_data()
        print("🏁 Teste concluído.")

if __name__ == "__main__":
    test_pipeline()
